// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    highest_exposure_lines: {
        name: "highest_exposure_lines";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: unknown;
      };
    risk_mix_by_plant: {
        name: "risk_mix_by_plant";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: unknown;
      };
    vibration_trend: {
        name: "vibration_trend";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: unknown;
      };
  }
}
